export { Movies } from './Movies'
export { MovieDetail } from './MovieDetail'
export { Search } from './Search'
export { Configuration } from './Configuration'
export { MovieTrailer } from './MovieTrailer'
